// <auto-generated />
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.DataAccess.Migrations
{
    [DbContext(typeof(DtatContext))]
    partial class DtatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulky.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Science fiction"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("Price100")
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("Price50")
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "J.D. Salinger",
                            CategoryId = 1,
                            Description = "A novel about a teenage boy's experiences and thoughts in the days following his expulsion from a prestigious prep school.",
                            ISBN = "0316769177",
                            ImageUrl = "",
                            ListPrice = 99.99m,
                            Price = 97.99m,
                            Price100 = 84.99m,
                            Price50 = 89.99m,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            CategoryId = 2,
                            Description = "A novel set in the American South during the 1930s, dealing with racial injustice and moral growth through the eyes of a young girl.",
                            ISBN = "0060935464",
                            ImageUrl = "",
                            ListPrice = 79.99m,
                            Price = 78.39m,
                            Price100 = 67.99m,
                            Price50 = 71.99m,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 3,
                            Author = "F. Scott Fitzgerald",
                            CategoryId = 1,
                            Description = "A novel depicting the lavish and decadent lifestyle of the wealthy elite in the Roaring Twenties, and the disillusionment and emptiness that lies beneath.",
                            ISBN = "0743273567",
                            ImageUrl = "",
                            ListPrice = 129.99m,
                            Price = 127.39m,
                            Price100 = 110.49m,
                            Price50 = 116.99m,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            CategoryId = 3,
                            Description = "A classic romance novel about the Bennet family and their five daughters, particularly the headstrong Elizabeth Bennet and her budding relationship with the wealthy Mr. Darcy.",
                            ISBN = "0141439513",
                            ImageUrl = "",
                            ListPrice = 59.99m,
                            Price = 58.79m,
                            Price100 = 50.99m,
                            Price50 = 53.99m,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Aria Blackwell",
                            CategoryId = 2,
                            Description = "A thrilling space opera about a group of explorers who embark on a dangerous journey to uncover the truth behind an ancient alien artifact.",
                            ISBN = "9781534453542",
                            ImageUrl = "",
                            ListPrice = 99.99m,
                            Price = 97.99m,
                            Price100 = 84.99m,
                            Price50 = 89.99m,
                            Title = "The Stars Beyond"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Xander Steele",
                            CategoryId = 2,
                            Description = "A gripping tale of a lone starship captain who must navigate through treacherous space battles and unravel a conspiracy that threatens the fate of the galaxy.",
                            ISBN = "9781982143463",
                            ImageUrl = "",
                            ListPrice = 79.99m,
                            Price = 78.39m,
                            Price100 = 67.99m,
                            Price50 = 71.99m,
                            Title = "Nebula's Edge"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Zara Nova",
                            CategoryId = 4,
                            Description = "A mind-bending story of time travel and alternate realities, where the fate of humanity hangs in the balance as a group of unlikely heroes race against time to save the future.",
                            ISBN = "9781728314557",
                            ImageUrl = "",
                            ListPrice = 129.99m,
                            Price = 127.39m,
                            Price100 = 110.49m,
                            Price50 = 116.99m,
                            Title = "Time Warp Chronicles"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Raven Cross",
                            CategoryId = 4,
                            Description = "A gritty cyberpunk tale set in a dystopian future, where a lone hacker fights against corrupt corporations and ruthless mercenaries in a battle for survival.",
                            ISBN = "9781954893208",
                            ImageUrl = "",
                            ListPrice = 59.99m,
                            Price = 58.79m,
                            Price100 = 50.99m,
                            Price50 = 53.99m,
                            Title = "Cyberpunk Revolution"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Models.Product", b =>
                {
                    b.HasOne("Bulky.Models.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
